= About
2018-02-12
:jbake-type: page
:jbake-status: published

I am a father, husband, software developer, veteran, barber, dish washer and landlord. This blog is about technology
and software development.

http://groovy-lang.org/[Groovy] and https://nixos.org/[nixos] are my latest interest. I spend my nights after the kids
are in bed working on my https://nixos.org/[nixos] install or https://github.com/moaxcp/graph-dsl[graph-dsl].

I stated learning http://groovy-lang.org/[groovy] when I volunteered to convert a large http://ant.apache.org/[ant]
build to https://gradle.org/[gradle]. http://groovy-lang.org/[Groovy]'s support for
http://groovy-lang.org/processing-xml.html#_xmlparser_and_xmlslurper[reading xml] and
http://groovy-lang.org/templating.html#_template_framework[templating] is simply the best. Once the project was
converted I was back to using java until I decided to start a small project called graph-dsl.

https://github.com/moaxcp/graph-dsl[Graph-dsl] was inspired by the DAG in gradle. I also wanted to learn a lot of
topics we talk about at work. Test driven development, continous delivery, automating everything and generally removing
human error. Graph-dsl is a result of my disciplined approach to creating a library. It may not be very practical to
other developers but graphs have always interested me.

Nixos became my primary OS after lots of trial and error with gentoo. I learned a lot about linux with gentoo but it
seemed so easy to forget how the system was setup and how to fix blocked packages. Nixos allows you to configure the
entire system in a declarative language called nix so you always know how the system is configured. Blocked packages
are impossible in nixos. It was also a good chance to learn systemd.

The purpose of this blog is to write about topics I am interested in and be helpful to others with similar interests.