Notes from updating visualvm in nix

==fetchzip

fetchzip uses "source" as the name by default. Only name and checksum affect the path within the nix 
store. Just changing the url may result in the wrong file being used. For visualvm I needed to change 
the url and sha256. sha256 is a hash of the content of the zip file not the zip file itself. To get the 
hash use nix-prefetch-url with the attribute to fetch. In the case of visualvm use

----
nix-prefetch-url -A visualvm.src
----

Will download src attribute to current directory. The default name of the dir is source. If the hash 
doesn't match a message will display the correct hash. The hash is not of the archive it is a 
deterministic hash of the contents of the archive. You cannot run sha256sum on the file and expect it 
to be correct.

==building

From nixpkgs repo run 

----
nix-build -A visualvm
----

This will build the package.

==installing

----
nix-env -iA visualvm -f .
----

This will install the package for the user environment.
